# This file was generated by GoReleaser. DO NOT EDIT.
cask "mistah" do
  version "0.6.2"

  on_macos do
    on_arm do
      sha256 "bc1d656919a9e52ee4da3398b3a4685678bd373577796212fcea17ae73a0fa83"
      url "https://github.com/sistematlan/mistah/releases/download/v#{version}/mistah_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "456974ef359516ce04897616ecbd5ac1b6f518ceefb2fe9b925f46699e14040d"
      url "https://github.com/sistematlan/mistah/releases/download/v#{version}/mistah_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_intel do
      sha256 "e8209ebf09d9257cab0935969793ccb25e64ff40851da781074c04b1fe521c73"
      url "https://github.com/sistematlan/mistah/releases/download/v#{version}/mistah_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mistah"
  desc "CLI open-source que recupera espacio en disco: cachés, papelera, backups viejos y más. Sin telemetría, código auditable."
  homepage "https://mistah.sistematlan.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mistah"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mistah"]
    end
  end

  # No zap stanza required
end
