# This file was generated by GoReleaser. DO NOT EDIT.
cask "mistah" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "a362c67adeec3e380a4fa52731e2f80b082088a51c010b8277abedf710ae8644"
      url "https://github.com/sistematlan/mistah/releases/download/v#{version}/mistah_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1f9b5720dd52360997edbe95a0a6ba707b43f4507ed639e762c1d9b1fab78a88"
      url "https://github.com/sistematlan/mistah/releases/download/v#{version}/mistah_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_intel do
      sha256 "e022e85220aaa7f5e3dc84e845f5e1b25434c35c13c2906678d06cfc3d08a0c8"
      url "https://github.com/sistematlan/mistah/releases/download/v#{version}/mistah_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mistah"
  desc "CLI open-source que recupera espacio en disco: cachés, papelera, backups viejos y más. Sin telemetría, código auditable."
  homepage "https://mistah.sistematlan.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mistah"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mistah"]
    end
  end

  # No zap stanza required
end
