# This file was generated by GoReleaser. DO NOT EDIT.
cask "mistah" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "9a922ad2c97fabb1316ee0a39e8d8628307a9bd3e179cd5c6bcfd6c56d72974e"
      url "https://github.com/sistematlan/mistah/releases/download/v#{version}/mistah_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b7b991eea03089d0b7f87311e67205cad1d902bae022b517eef4588505e8d8d5"
      url "https://github.com/sistematlan/mistah/releases/download/v#{version}/mistah_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_intel do
      sha256 "46ac4ac4fd91b3534c86067ae45c0d6d3fb6b21f4d50b15e8b0b1df1c2ec5ee1"
      url "https://github.com/sistematlan/mistah/releases/download/v#{version}/mistah_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mistah"
  desc "CLI open-source que recupera espacio en disco: cachés, papelera, backups viejos y más. Sin telemetría, código auditable."
  homepage "https://mistah.sistematlan.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mistah"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mistah"]
    end
  end

  # No zap stanza required
end
